name: nonpareil-cm
base: core18
summary: A high-fidelity simulator for calculators
description: |
  Nonpareil simulates many HP calculators models introduced between 1972
  and 1982. Simulation fidelity is achieved through the use of the actual
  microcode of the calculators, thus in most cases the simulation behavior
  exactly matches that of the real calculator. In particular, numerical
  results will be identical, because the simulator is using the BCD
  arithmetic algorithms from the calculator.
grade: devel
confinement: strict
adopt-info: nonpareil

apps:
  nonpareil-cm:
    command: usr/bin/nonpareil
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "21":
    command: usr/bin/21
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "25":
    command: usr/bin/25
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "32e":
    command: usr/bin/32e
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "33c":
    command: usr/bin/33c
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "34c":
    command: usr/bin/34c
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "35":
    command: usr/bin/35
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "35":
    command: usr/bin/35
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "37e":
    command: usr/bin/37e
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "38c":
    command: usr/bin/38c
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "38e":
    command: usr/bin/38e
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "41cv":
    command: usr/bin/41cv
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "41cx":
    command: usr/bin/41cx
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "45":
    command: usr/bin/45
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "55":
    command: usr/bin/55
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  "80":
    command: usr/bin/80
    plugs:
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - pulseaudio
      - audio-playback
      - mount-observe
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

  modutil:
    command: usr/bin/modutil
    plugs:
      - home

  uasm:
    command: usr/bin/uasm
    plugs:
      - home

parts:
  nonpareil:
    plugin: nil
    source: https://nonpareil.brouhaha.com/download/nonpareil-0.79.tar.gz
    after: [patches, scons]
    build-packages:
      - build-essential
      - libsdl-dev
      - libgtk2.0-dev
      - libxml2-dev
      - flex
    stage-packages:
      - libsdl1.2debian
      - libglu1-mesa
      - libgtk2.0-0
      - libslang2
    override-pull: |
      snapcraftctl pull
      version=$(sed -n '/^release =/s/.*'"'"'\(.*\)'"'"'.*/\1/p' < SConstruct)
      snapcraftctl set-version "$version"
      patch -d "$SNAPCRAFT_PART_SRC" -p1 < "$SNAPCRAFT_STAGE"/fix-zlib-include.diff
    override-build: |
      scons prefix=/usr
      scons install prefix=/usr destdir="$SNAPCRAFT_PART_INSTALL"
      for model in 21 25 32e 33c 34c 35 37e 38c 38e 41cv 41cx 45 55 80; do
        ln -v "$SNAPCRAFT_PART_INSTALL"/usr/bin/nonpareil "$SNAPCRAFT_PART_INSTALL"/usr/bin/$model; \
      done
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -usr/share/icons

  scons:
    plugin: python
    python-version: python2
    source: https://sourceforge.net/projects/scons/files/scons/1.0.0/scons-1.0.0.tar.gz
    prime:
      - -*

  patches:
    plugin: dump
    source: patches
    prime:
      - -*

layout:
  /usr/lib/nonpareil:
    symlink: $SNAP/usr/lib/nonpareil
